# Develop profile (don't communicate with services, only send information to console)
spring.config.activate.on-profile=develop
# Telegram_develop
tg.username=anton415_check_dev_bot
tg.token=8683111071:AAEdHpvO6-Yx3KoqCq7mMp8GtXBCV8wefbc
